<?php
// $Id$

/**
 * Implementation of hook_menu().
 */
function feeds_tamper_menu() {
  $items = array();
  $items['admin/build/feeds_tamper/%ctools_js/plugins/%plugin'] = array(
    'page callback' => 'feeds_tamper_modal',
    'page arguments' => array(3),
    'access arguments' => array('administer feeds tamper'),
    //'file' => 'feeds_tamper.admin.inc',
    //'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implementation of hook_ctools_plugin_api().
 */
function feeds_tamper_ctools_plugin_api($owner, $api) {
  if ($owner == 'feeds_tamper' && $api == 'feeds_tamper_preset') {
    return array('version' => 1);
  }
}

/**
* Implementation of hook_ctools_plugin_directory().
*/
function feeds_tamper_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && $plugin == 'export_ui') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implementation of hook_ctools_plugin_plugins().
 *
 * Psuedo hook defintion plugin system options and defaults.
 */
function feeds_tamper_ctools_plugin_plugins() {
  return array(
    'cache' => TRUE,
    'use hooks' => TRUE,
  );
}

/**
 * Implementation of hook_feeds_tamper_plugins().
 */
function feeds_tamper_feeds_tamper_plugins() {
  module_load_include('inc', 'feeds_tamper', 'feeds_tamper.plugins');
  return _feeds_tamper_feeds_tamper_plugins();
}

/**
 * @defgroup plugins Plugin functions
 * @{
 */

/**
 * Gets all available plugins.
 *
 * @return
 *   An array where the keys are the plugin keys and the values
 *   are the plugin info arrays as defined in hook_feeds_tamper_plugins().
 */
function feeds_tamper_get_plugins() {
  ctools_include('plugins');
  $plugins = ctools_get_plugins('feeds_tamper', 'plugins');

  // Sort plugins by name and return.
  uasort($plugins, 'feeds_plugin_compare');
  return $plugins;
}

/**
* Implementation of hook_theme
*/
function feeds_tamper_theme() {
  return array(
    'feeds_tamper_list_sort_form' => array(
      'arguments' => array('form' => NULL),
    ),
  );
}

function feeds_tamper_modal($js = FALSE, $plugin) {
  $output = t('<p>Lorem ipsum dolor sit amet...</p>' . $plugin);
  $title = t('Modal example');
  if ($js) {
    ctools_include('ajax');
    ctools_include('modal');
    ctools_modal_render($title, $output);
    // above command will exit().
  }
  else {
    drupal_set_title($title);
    return $output;
  }
}
